### PR TITLE
Fix bug where deasync binary isn't in Windows build

### LINKED ISSUE #369: Deasync.node is not included in the zip file when we build from windows os
## What would you like to change?
zapier build and zapier push do not include the deasync.node which is needed from the zapier-platform-legacy-scripting-runner in the build.zip file when we run the build command from windows.
The reason is that the path separator is not '/' in windows so the condition in build.js
```
filePath.endsWith(`/bin/linux-x64-node-${nodeMajorVersion}/deasync.node`)
```
never returns true.

Maybe you could check the separator as you already do in 
```
filePath.match(path.sep === '\\' ? /aws-sdk\\apis\\.*\.json/ : /aws-sdk\/apis\/.*\.json/)
```
 
* CLI Version (`zapier -v`): 7.3.0
* Operating System and version: windows 10

### PR DESCRIPTION
**Pull request by eliangcs**
Fixes #369.

### CODE REVIEW

File: src/utils/build.js [hunk 1]
```diff
@@ -178,7 +178,12 @@ const forceIncludeDumbPath = (appConfig, filePath) => {
   return (
     filePath.endsWith('package.json') ||
     filePath.endsWith('definition.json') ||
-    filePath.endsWith(`/bin/linux-x64-node-${nodeMajorVersion}/deasync.node`) || // Special, for zapier-platform-legacy-scripting-runner
+    filePath.endsWith(
+      // Special, for zapier-platform-legacy-scripting-runner
+      path.sep === '\\'
```
Comment (xavdid) [inline src/utils/build.js]: You can change this whole ternary to use `path.join`, which takes care of detecting and using the separator correctly. Same goes for above, and basically any other use of `path.sep`.

```js
filePath.endsWith(path.join('bin', `linux-x64-node-${nodeMajorVersion}`, 'deasync.node'))
```
